[manager]
ratio = [ 1, 3, 4 ]

[opener]
edit = [
  { run = 'nvim %*', block = true, desc = "nvim", for = "windows" },
]

[preview]
max_width     = 900
max_height    = 900
image_delay   = 100
image_quality = 90
